/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conceptium.biz;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author MathomeTD
 */
public class Incident extends javax.swing.JFrame {
//private static Incident obj = null;
    /**
     * Creates new form Incident
     */
    DbConnection connect = new DbConnection();
    public Incident() throws SQLException {
        setUndecorated(true);
        setResizable(false);
        initComponents();
        fillId();
        supervisor();
        
        txtReferenceNumber.setBackground(Color.GREEN);
        txtReferenceNumber.setFont(new Font("Arial", Font.BOLD, 14));
        txtReferenceNumber.setEditable(false);
        //fillOccurance();
    }
    private  int staffId;
    private static final AtomicInteger counter = new AtomicInteger(0);
    private void setReferenceNumber(){
        String sql = "select SHE_ID from AUTOSHE";
        try(Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Incidents", "herbert", "elsie1*#");
            PreparedStatement pst = con.prepareStatement(sql,ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                ResultSet rs = pst.executeQuery()){
            rs.afterLast();
            if(rs.last()){
            staffId = rs.getInt("SHE_ID");
            //if(staffId == 0){ staffId = +1;
            txtReferenceNumber.setText("SHE-"+ staffId);
            //staffId ++;
            //staffId = counter.incrementAndGet();
            //}
            //staffId ++;
            txtReferenceNumber.setText("SHE-"+ staffId);
            staffId ++;
            //staffId = counter.incrementAndGet();
            }
        }catch(SQLException e){
        JOptionPane.showMessageDialog(Incident.this, e + "Unable to set counter");}
    }
   private void fillId() throws SQLException{
        String sql ="Select * from Persons";
            try {
                Connection con = connect.dbConnection();
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    String ID = rs.getString("EmployeeNumber");
                    cboEmployeeNumber.addItem(ID.trim());
                }
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
            
    }
        private void supervisor() throws SQLException{
        String sql ="Select * from Site";
            try {
                Connection con = connect.dbConnection();
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    String ID = rs.getString("Supervisor");
                    cboReportedTo.addItem(ID.trim());
                }
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
        
        
        //public static Incident getObj(){
            //if (obj == null){
                //obj = new Incident();
            //}
            //return obj;
        //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        statusOpen = new javax.swing.JCheckBox();
        statusClosed = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdNumber = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        cboEmployeeNumber = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cboReportedTo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtSite = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cboIncidentType = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cboNature = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cboNOCDW = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        cboHrs = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        cboShift = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        txtYears = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtReferenceNumber = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtEquipmentUsed = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        cboAgent = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        txtTimeExposed = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtEstimatedValue = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dcClosingDate = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtActivity = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtEquipmentDemaged = new javax.swing.JTextField();
        dcTodayDate = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel27.setText("Incident Status:");

        statusOpen.setText("Open");
        statusOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusOpenActionPerformed(evt);
            }
        });

        statusClosed.setText("Closed");
        statusClosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusClosedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusOpen)
                .addGap(95, 95, 95)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(statusClosed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusOpen)
                    .addComponent(statusClosed)
                    .addComponent(jLabel27)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Employee ID::");

        jLabel2.setText("ID Number:");

        jLabel3.setText("Name:");

        jLabel4.setText("Surname:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        cboEmployeeNumber.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEmployeeNumberItemStateChanged(evt);
            }
        });
        cboEmployeeNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEmployeeNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSurname))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cboEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdNumber)))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Reported To:");

        cboReportedTo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboReportedToItemStateChanged(evt);
            }
        });

        jLabel10.setText("Contact Number:");

        jLabel28.setText("Email:");

        jLabel11.setText("Department:");

        jLabel18.setText("Site:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel11)
                    .addComponent(jLabel28)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSite)
                    .addComponent(cboReportedTo, 0, 240, Short.MAX_VALUE)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.Alignment.LEADING)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboReportedTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Incident Type:");

        cboIncidentType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal Injury", "Property Demage", "Near miss", "Non Related" }));
        cboIncidentType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboIncidentTypeItemStateChanged(evt);
            }
        });
        cboIncidentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIncidentTypeActionPerformed(evt);
            }
        });

        jLabel12.setText("Nature:");

        cboNature.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNatureItemStateChanged(evt);
            }
        });
        cboNature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNatureActionPerformed(evt);
            }
        });

        jLabel7.setText("Date of Incident:");

        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        jDateChooser2.setDateFormatString("dd/MM/yyyy");
        jDateChooser2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jDateChooser2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDateChooser2MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDateChooser2MouseEntered(evt);
            }
        });
        jDateChooser2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jDateChooser2InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });
        jDateChooser2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooser2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooser2KeyReleased(evt);
            }
        });

        jLabel8.setText("Date of reporting:");

        jLabel15.setText("Days worked:");

        cboNOCDW.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cboNOCDW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNOCDWActionPerformed(evt);
            }
        });

        jLabel16.setText("Hr on shift:");

        cboHrs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        jLabel17.setText("Shift:");

        cboShift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "Night" }));

        jLabel21.setText("Experience:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel12)
                        .addComponent(jLabel7))
                    .addComponent(jLabel8)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboHrs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboShift, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtYears))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboNOCDW, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(cboNature, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboIncidentType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboIncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cboNature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(cboShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cboNOCDW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cboHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Reference Number:");

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setText("Equipment that was bieng used:");

        txtEquipmentUsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEquipmentUsedActionPerformed(evt);
            }
        });

        jLabel19.setText("Select body part injured if any:");

        jRadioButton1.setText("Head/Neck");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Eye");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Trunk");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Finger");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("Hand");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("Arm");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setText("Foot");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setText("Toe");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addGap(33, 33, 33))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6)
                        .addGap(0, 0, 0)
                        .addComponent(jRadioButton7)
                        .addGap(0, 0, 0)
                        .addComponent(jRadioButton8))
                    .addComponent(txtEquipmentUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEquipmentUsed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cboAgent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Applicable", "Gas", "Chemical" }));
        cboAgent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAgentItemStateChanged(evt);
            }
        });
        cboAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAgentActionPerformed(evt);
            }
        });

        jLabel25.setText("Time exposed:");

        txtTimeExposed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeExposedActionPerformed(evt);
            }
        });

        jLabel23.setText("Estimated Value:");

        jLabel30.setText("Closing Date:");

        jLabel24.setText("Agent:");

        dcClosingDate.setDateFormatString("dd/MM/yyyy");
        dcClosingDate.setDate(null);
        dcClosingDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dcClosingDateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dcClosingDateMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dcClosingDateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dcClosingDateMouseEntered(evt);
            }
        });
        dcClosingDate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                dcClosingDateInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        dcClosingDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcClosingDatePropertyChange(evt);
            }
        });
        dcClosingDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcClosingDateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dcClosingDateKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstimatedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcClosingDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimeExposed))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtTimeExposed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstimatedValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel30))
                    .addComponent(dcClosingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtActivity.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                //if(cboNature.getSelectedItem().toString().equals("Above R50 000")||cboNature.getSelectedItem().toString().equals("Fatality")){
                    //txtReferenceNumber.setBackground(Color.RED);
                    //}else{
                    //txtReferenceNumber.setBackground(Color.GREEN);}
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                //if(cboNature.getSelectedItem().toString().equals("Above R50 000")||cboNature.getSelectedItem().toString().equals("Fatality")){
                    //txtReferenceNumber.setBackground(Color.RED);
                    //}else{
                    //txtReferenceNumber.setBackground(Color.GREEN);}

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                //format.format(Integer.parseInt(txtTest.getText();
                    //System.out.println(format.format(Integer.parseInt(txtTest.getText())));
                    //jFormattedTextField1.setValue(Double.parseDouble(txtTest.getText()));
                }
            });
            txtActivity.setColumns(20);
            txtActivity.setRows(5);
            txtActivity.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtActivityKeyTyped(evt);
                }
            });
            jScrollPane2.setViewportView(txtActivity);

            jLabel20.setText("Activity bieng carried out:");

            javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
            jPanel8.setLayout(jPanel8Layout);
            jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addComponent(jLabel20)
                    .addContainerGap(210, Short.MAX_VALUE))
                .addComponent(jScrollPane2)
            );
            jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel20)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2)
                    .addGap(0, 0, 0))
            );

            jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/edit.png"))); // NOI18N
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/close.png"))); // NOI18N
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/save.png"))); // NOI18N
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jLabel26.setText("Area:");

            jLabel22.setText("Equipment Demaged:");

            txtEquipmentDemaged.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtEquipmentDemagedActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
            jPanel9.setLayout(jPanel9Layout);
            jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(txtArea)
                .addComponent(txtEquipmentDemaged, javax.swing.GroupLayout.Alignment.TRAILING)
            );
            jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(jLabel26)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel22)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtEquipmentDemaged, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            dcTodayDate.setDateFormatString("dd/MM/yyyy");

            jLabel29.setText("Date:");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dcTodayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtReferenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 361, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dcTodayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtReferenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGap(0, 0, 0)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            jPanel10.setBackground(new java.awt.Color(255, 255, 255));

            javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
            jPanel10.setLayout(jPanel10Layout);
            jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 41, Short.MAX_VALUE)
            );

            jPanel11.setBackground(new java.awt.Color(255, 255, 255));

            javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
            jPanel11.setLayout(jPanel11Layout);
            jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 32, Short.MAX_VALUE)
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(4, 4, 4)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!txtActivity.getText().equals("")){
        //if(jDateChooser1.getDate(null)){}
        String name = txtName.getText();
        String surname = txtSurname.getText();
        String idNumber = txtIdNumber.getText();
        String employeeNumber = cboEmployeeNumber.getSelectedItem().toString();
        String referenceNumber = txtReferenceNumber.getText();
        String incidentType = cboIncidentType.getSelectedItem().toString();
        String natureOfIncident = cboNature.getSelectedItem().toString();
        String shift = cboShift.getSelectedItem().toString();
        String hoursOnShift = cboHrs.getSelectedItem().toString();
        String reportTo = cboReportedTo.getSelectedItem().toString();
        String numberOfContiniousDaysWorked = cboNOCDW.getSelectedItem().toString();
        String contactNumber = txtContactNumber.getText();
        String contactEmail = txtEmail.getText();
        String department = txtDepartment.getText();
        String site = txtSite.getText();
        String equipmentUsed = txtEquipmentUsed.getText();
        String activityBiengDone = txtActivity.getText();
        String yearsOfExperience = txtYears.getText();
        String agent = cboAgent.getSelectedItem().toString();
        String timeExposed = txtTimeExposed.getText();
        String equipmentDemaged = txtEquipmentDemaged.getText();
        String estimatedValue = txtEstimatedValue.getText();
        String head_Neck = choice;
        String eye = choice;
        String truck = choice;
        String finger = choice;
        String hand = choice;
        String arm = choice;
        String foot = choice;
        String toe = choice;
        String area = txtArea.getText();
        if(statusOpen.isSelected()){
        status = "Open";
        }else{
        status = "Closed";}
        //String open = status;
        //String status = txtStatus.getText();
        /**DbaseOperation Db = new DbaseOperation();
        String[] arr = {name,surname,idNumber,employeeNumber,referenceNumber,incidentType,natureOfIncident,shift,
            hoursOnShift,reportTo,numberOfContiniousDaysWorked,contactNumber,contactEmail,department,site,equipmentUsed,activityBiengDone,
        yearsOfExperience,agent,timeExposed,equipmentDemaged,estimatedValue,head_Neck,eye,truck,finger,hand,arm,foot,toe,
        area,status};
        Db.insertToDb("Incident","Name,Surname,IDNumber,EmployeeNumber,ReferenceNumber,"+
                "IncidentType,NatureOfIncident,DateOfIncident,DateOfReportingIncident,Shift,HoursOnShift,"+
                "ReportedTo,NumberOfContinuosDaysWorked,ContactNumber,ContactEmail,Department,Site,"+
                "EquipmentUsed,Head_Neck,Eye,Trunk,Finger,Head,Arm,Foot,Toe,ActivityBiengCarriedOut,"+
                "YearsOfExperienceOnTask,EquipmentDemaged,EstimatedValue,Area,Status,Agent,"+
                "TimeOfExpose" , "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?", arr);
                JOptionPane.showMessageDialog(Incident.this, "incident"+" "+ referenceNumber+ " "+ "successfully saved.");**/
        String sql = "insert into Incident(Name,Surname,IDNumber,EmployeeNumber,ReferenceNumber,"+
                "IncidentType,NatureOfIncident,DateOfIncident,DateOfReportingIncident,Shift,HoursOnShift,"+
                "ReportedTo,NumberOfContinuosDaysWorked,ContactNumber,ContactEmail,Department,Site,"+
                "EquipmentUsed,Head_Neck,Eye,Trunk,Finger,Head,Arm,Foot,Toe,ActivityBiengCarriedOut,"+
                "YearsOfExperienceOnTask,EquipmentDemaged,EstimatedValue,Area,Status,Agent,TimeOfExpose,"+
                "TodayDate,ClosingDate)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try(Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
        PreparedStatement pst = con.prepareStatement(sql);){
        pst.setString(1, name);
        pst.setString(2, surname);
        pst.setString(3, idNumber);
        pst.setString(4, employeeNumber);
        pst.setString(5, referenceNumber);
        pst.setString(6, incidentType);
        pst.setString(7, natureOfIncident);
        pst.setDate(8, new java.sql.Date(jDateChooser1.getDate().getTime()));
        pst.setDate(9, new java.sql.Date(jDateChooser2.getDate().getTime()));
        pst.setString(10, shift);
        pst.setString(11, hoursOnShift);
        pst.setString(12, reportTo);
        pst.setString(13, numberOfContiniousDaysWorked);
        pst.setString(14, contactNumber);
        pst.setString(15, contactEmail);
        pst.setString(16, department);
        pst.setString(17, site);
        pst.setString(18, equipmentUsed);
        pst.setString(19,head_Neck);
        pst.setString(20,eye);
        pst.setString(21,truck);
        pst.setString(22,finger);
        pst.setString(23,hand);
        pst.setString(24,arm);
        pst.setString(25,foot);
        pst.setString(26,toe);
        pst.setString(27, activityBiengDone);
        pst.setString(28, yearsOfExperience);
        pst.setString(29, equipmentDemaged);
        pst.setString(30, estimatedValue);
        pst.setString(31, area);
        pst.setString(32, status);
        pst.setString(33, agent);
        pst.setString(34, timeExposed);
        pst.setDate(35, new java.sql.Date(dcTodayDate.getDate().getTime()));
        pst.setDate(36, null);
        pst.executeUpdate();
        JOptionPane.showMessageDialog(Incident.this, "incident"+" "+ referenceNumber+ " "+ "successfully saved.");
            System.out.println(status);
        
        DashBoards.overDue();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Incident.this, e);
        }
        this.dispose();
        IncidentDetails iD = IncidentDetails.getObj();
        iD.cboReference.removeAllItems();
        String sql1 = "select * from Incident where ReferenceNumber = ?";
        String ref = txtReferenceNumber.getText();
        try{
        Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
        PreparedStatement pst = con.prepareStatement(sql1);
        pst.setString(1, ref);
        ResultSet rs = pst.executeQuery();
        while(rs.next()){
            String reference = rs.getString("ReferenceNumber");
            IncidentDetails.cboReference.addItem(reference);
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(Incident.this, e);
        }
        String sql2 = "insert into AUTOSHE(SHE_ID) values(?)";
        try(Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Incidents", "herbert", "elsie1*#");
            PreparedStatement pst = con.prepareStatement(sql2);){
            pst.setInt(1, staffId);
            pst.executeUpdate();
        }catch(SQLException e){
        JOptionPane.showMessageDialog(Incident.this, e + "Unable to set counter");}
       // SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Calendar c = Calendar.getInstance();
                //c.setTime(new Date());
                c.setTime(jDateChooser2.getDate());
                //c.setTime(sdf.parse(dateChooserCombo1.getSelectedDate().toString()));
                //int x = Integer.parseInt(txtDays.getText());
                c.add(Calendar.DATE, 30);
                //SimpleDateFormat print = new SimpleDateFormat("yyyy/MM/dd");
                IncidentDetails.jDateChooser1.setDate(c.getTime());
                //IncidentDetails.txtDate.setText(sdf.format(c.getTime()));
                //IncidentDetails.txtDate.setEnabled(false);
        //updateTable();
        iD.setVisible(true);
        this.dispose();}
        else{
        JOptionPane.showMessageDialog(Incident.this, "Please complete the activitity which was bieng done");}
    }//GEN-LAST:event_jButton1ActionPerformed
public void fillName(){
    String select = cboEmployeeNumber.getSelectedItem().toString();
        try{
            Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
            PreparedStatement pst = con.prepareStatement("Select * from Persons where EmployeeNumber = ?");
            pst.setString(1, select);
            ResultSet rs = pst.executeQuery();
            if (rs.next()){
                String name = rs.getString("Name");
                txtName.setText(name.trim());
                String surname = rs.getString("Surname");
                txtSurname.setText(surname.trim());
                String idNumber = rs.getString("IDNumber");
                txtIdNumber.setText(idNumber);
            }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(Incident.this, e);
        }
}

public void fillSite(){
    String select = cboEmployeeNumber.getSelectedItem().toString();
        try{
            Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
            PreparedStatement pst = con.prepareStatement("Select * from Site where EmployeeNumber = ?");
            pst.setString(1, select);
            ResultSet rs = pst.executeQuery();
            if (rs.next()){
                String name = rs.getString("Supervisor");
                cboReportedTo.setSelectedItem(name);
            }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(Incident.this, e);
        }
}
public void fillsupervisor(){
    String search = cboReportedTo.getSelectedItem().toString();
        String sql = "select * from Person where EmployeeNumber = ?";
        try{
            Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
            PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, search);
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    String ID = rs.getString("ContactNumber");
                    txtContactNumber.setText(ID.trim());
                    String email = rs.getString("EmailAddress");
                    txtEmail.setText(email.trim());
                    String department = rs.getString("Department");
                    txtDepartment.setText(department.trim());
                    String site = rs.getString("Site");
                    txtSite.setText(site.trim());
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Incident.this, e);
        }
}
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        dcTodayDate.setEnabled(false);
        dcClosingDate.setEnabled(false);
        

//staffId = counter.incrementAndGet();
        //setReferenceNumber();
        Locale RSA = new Locale("en", "ZA");
        NumberFormat format = NumberFormat.getCurrencyInstance(RSA);
        format.setMaximumFractionDigits(2);

        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setMinimum(0.00);
        formatter.setMaximum(1000000000.00);
        formatter.setAllowsInvalid(false);
        formatter.setOverwriteMode(true);

        DefaultFormatterFactory dff = new DefaultFormatterFactory(formatter);
        txtEstimatedValue.setFormatterFactory(dff);
        txtEstimatedValue.setValue(0.00);

        txtEstimatedValue.setBackground(Color.green);
        txtTimeExposed.setEnabled(false);
        txtTimeExposed.setText("0");

        txtActivity.setWrapStyleWord(true);
        txtActivity.setLineWrap(true);
        //txtStatus.setEnabled(false);
        //txtStatus.setText("Open");
        //txtStatus.setBackground(Color.RED);
        //txtStatus.setFont(new Font("Arial", Font.BOLD, 14));
        String search = cboIncidentType.getSelectedItem().toString();
        String sql1 ="Select * from IncidentOccurrance where IncidentType = ?";
            //String sql = "select * from IncidentOccurance";
            try {
                Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
                PreparedStatement pst = con.prepareStatement(sql1);
                pst.setString(1, search);
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    String incidentResult = rs.getString("Nature");
                    cboNature.addItem(incidentResult.trim());
                    //String description = rs.getString("Description");
                    //txtDescription.setText(description.trim());
                    //txtDescription.setLineWrap(true);
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
            fillsupervisor();
            //fillName();
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        choice = "head_Neck";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        choice = "eye";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        choice = "truck";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        choice = "finger";
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        choice = "hand";
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        choice = "arm";
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        choice = "foot";
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        choice = "toe";
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void txtEquipmentUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEquipmentUsedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEquipmentUsedActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void cboIncidentTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboIncidentTypeItemStateChanged
        cboNature.removeAllItems();
        String search = cboIncidentType.getSelectedItem().toString();
        String sql ="Select * from IncidentOccurrance where IncidentType = ?";
            //String sql = "select * from IncidentOccurance";
            try {
                //Class.forName("org.sqlite.JDBC");
                //Connection con = DriverManager.getConnection("jdbc:sqlite:Incident");
                Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, search);
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    String incidentResult = rs.getString("Nature");
                    cboNature.addItem(incidentResult.trim());
                    //String description = rs.getString("Description");
                    //txtDescription.setText(description.trim());
                    //txtDescription.setLineWrap(true);
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_cboIncidentTypeItemStateChanged

    private void cboReportedToItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboReportedToItemStateChanged
        String search = cboReportedTo.getSelectedItem().toString();
        String [] args = search.split(" ");
        String sql = "select * from Persons where EmployeeNumber = ?";
        try{
        Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
            PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, args[0]);
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    String ID = rs.getString("ContactNumber");
                    txtContactNumber.setText(ID.trim());
                    String email = rs.getString("EmailAddress");
                    txtEmail.setText(email.trim());
                    String department = rs.getString("Department");
                    txtDepartment.setText(department.trim());
                    String site = rs.getString("Site");
                    txtSite.setText(site.trim());
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Incident.this, e);
        }
    }//GEN-LAST:event_cboReportedToItemStateChanged

    private void cboEmployeeNumberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEmployeeNumberItemStateChanged
        fillName();
    }//GEN-LAST:event_cboEmployeeNumberItemStateChanged

    private void cboAgentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAgentItemStateChanged
        if (cboAgent.getSelectedItem().equals("Not Applicable")){
            txtTimeExposed.setEnabled(false);
            txtTimeExposed.setText("0");
        }
        else{
            txtTimeExposed.setEnabled(true);
        }
        
    }//GEN-LAST:event_cboAgentItemStateChanged

    private void cboNOCDWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNOCDWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNOCDWActionPerformed

    private void txtEquipmentDemagedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEquipmentDemagedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEquipmentDemagedActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name = txtName.getText();
        String surname = txtSurname.getText();
        String idNumber = txtIdNumber.getText();
        String employeeNumber = cboEmployeeNumber.getSelectedItem().toString();
        String referenceNumber = txtReferenceNumber.getText();
        String incidentType = cboIncidentType.getSelectedItem().toString();
        String natureOfIncident = cboNature.getSelectedItem().toString();
        String shift = cboShift.getSelectedItem().toString();
        String hoursOnShift = cboHrs.getSelectedItem().toString();
        String reportTo = cboReportedTo.getSelectedItem().toString();
        String numberOfContiniousDaysWorked = cboNOCDW.getSelectedItem().toString();
        String contactNumber = txtContactNumber.getText();
        String contactEmail = txtEmail.getText();
        String department = txtDepartment.getText();
        String site = txtSite.getText();
        String equipmentUsed = txtEquipmentUsed.getText();
        String activityBiengDone = txtActivity.getText();
        String yearsOfExperience = txtYears.getText();
        String agent = cboAgent.getSelectedItem().toString();
        String timeExposed = txtTimeExposed.getText();
        String equipmentDemaged = txtEquipmentDemaged.getText();
        String estimatedValue = txtEstimatedValue.getText();
        String head_Neck = choice;
        String eye = choice;
        String truck = choice;
        String finger = choice;
        String hand = choice;
        String arm = choice;
        String foot = choice;
        String toe = choice;
        String area = txtArea.getText();
        if(statusOpen.isSelected()){
        status = "Open";
        }else{
        status = "Closed";}
        //java.sql.Date dateOfIncident = new java.sql.Date(jDateChooser1.getDate().getTime());
        //java.sql.Date dateOfReporting = new java.sql.Date(jDateChooser2.getDate().getTime());
        //String status = txtStatus.getText();
        /**DbaseOperation Db = new DbaseOperation();
        String[] arr = {name,surname,idNumber,employeeNumber,referenceNumber,incidentType,natureOfIncident,shift,
            hoursOnShift,reportTo,numberOfContiniousDaysWorked,contactNumber,contactEmail,department,site,equipmentUsed,activityBiengDone,
        yearsOfExperience,agent,timeExposed,equipmentDemaged,estimatedValue,head_Neck,eye,truck,finger,hand,arm,foot,toe,
        area,status};
        Db.insertToDb("Incident","Name,Surname,IDNumber,EmployeeNumber,ReferenceNumber,"+
                "IncidentType,NatureOfIncident,DateOfIncident,DateOfReportingIncident,Shift,HoursOnShift,"+
                "ReportedTo,NumberOfContinuosDaysWorked,ContactNumber,ContactEmail,Department,Site,"+
                "EquipmentUsed,Head_Neck,Eye,Trunk,Finger,Head,Arm,Foot,Toe,ActivityBiengCarriedOut,"+
                "YearsOfExperienceOnTask,EquipmentDemaged,EstimatedValue,Area,Status,Agent,"+
                "TimeOfExpose" , "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?", arr);
                JOptionPane.showMessageDialog(Incident.this, "incident"+" "+ referenceNumber+ " "+ "successfully saved.");**/
        String sql = "update Incident set Name=?,Surname=?,IDNumber=?,EmployeeNumber=?,ReferenceNumber=?,"+
                "IncidentType=?,NatureOfIncident=?,DateOfIncident=?,"+
                "DateOfReportingIncident=?,Shift=?,HoursOnShift=?,ReportedTo=?,"+
                "NumberOfContinuosDaysWorked=?,ContactNumber=?,ContactEmail=?,Department=?,"+
                "Site=?,EquipmentUsed=?,Head_Neck=?,Eye=?,Trunk=?,Finger=?,Head=?,Arm=?,Foot=?,"+
                "Toe=?,ActivityBiengCarriedOut=?,YearsOfExperienceOnTask=?,EquipmentDemaged=?,"+
                "EstimatedValue=?,Area=?,Status=?,Agent=?,TimeOfExpose=?,TodayDate=?,ClosingDate=?"+
                "where ReferenceNumber='"+referenceNumber+"'";
        try(Connection con = DbConnection.dbConnection();
        PreparedStatement pst = con.prepareStatement(sql);){
        pst.setString(1, name);
        pst.setString(2, surname);
        pst.setString(3, idNumber);
        pst.setString(4, employeeNumber);
        pst.setString(5, referenceNumber);
        pst.setString(6, incidentType);
        pst.setString(7, natureOfIncident);
        pst.setDate(8, new java.sql.Date(jDateChooser1.getDate().getTime()));
        pst.setDate(9, new java.sql.Date(jDateChooser2.getDate().getTime()));
        pst.setString(10, shift);
        pst.setString(11, hoursOnShift);
        pst.setString(12, reportTo);
        pst.setString(13, numberOfContiniousDaysWorked);
        pst.setString(14, contactNumber);
        pst.setString(15, contactEmail);
        pst.setString(16, department);
        pst.setString(17, site);
        pst.setString(18, equipmentUsed);
        pst.setString(19,head_Neck);
        pst.setString(20,eye);
        pst.setString(21,truck);
        pst.setString(22,finger);
        pst.setString(23,hand);
        pst.setString(24,arm);
        pst.setString(25,foot);
        pst.setString(26,toe);
        pst.setString(27, activityBiengDone);
        pst.setString(28, yearsOfExperience);
        pst.setString(33, agent);
        pst.setString(34, timeExposed);
        pst.setString(29, equipmentDemaged);
        pst.setString(30, estimatedValue);
        pst.setString(31, area);
        pst.setString(32, status);
        pst.setDate(35, new java.sql.Date(dcTodayDate.getDate().getTime()));
        pst.setDate(36, new java.sql.Date(dcClosingDate.getDate().getTime()));
        pst.executeUpdate();
        JOptionPane.showMessageDialog(Incident.this, "incident"+" "+ referenceNumber+ " "+ "status saved.");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(Incident.this, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jDateChooser2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser2KeyReleased
        
    }//GEN-LAST:event_jDateChooser2KeyReleased

    private void jDateChooser2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MouseReleased

    }//GEN-LAST:event_jDateChooser2MouseReleased

    private void jDateChooser2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MousePressed
                
    }//GEN-LAST:event_jDateChooser2MousePressed

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
        
    }//GEN-LAST:event_jDateChooser2PropertyChange

    private void jDateChooser2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDateChooser2InputMethodTextChanged
        
    }//GEN-LAST:event_jDateChooser2InputMethodTextChanged

    private void jDateChooser2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser2KeyPressed
        
    }//GEN-LAST:event_jDateChooser2KeyPressed

    private void jDateChooser2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser2MouseClicked

    private void jDateChooser2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser2MouseEntered

    }//GEN-LAST:event_jDateChooser2MouseEntered

    private void statusOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusOpenActionPerformed
        status = "Open";
        if(statusOpen.isSelected()){
            //statusPending.setEnabled(false);
            statusClosed.setEnabled(false);
        }
        else{
            //statusPending.setEnabled(true);
            statusClosed.setEnabled(true);
        }
    }//GEN-LAST:event_statusOpenActionPerformed

    private void statusClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusClosedActionPerformed
        status = "Closed";
        if(statusClosed.isSelected()){
            statusOpen.setEnabled(false);
            //statusPending.setEnabled(false);
        }
        else{
            statusOpen.setEnabled(true);
            //statusPending.setEnabled(true);
        }
    }//GEN-LAST:event_statusClosedActionPerformed

    private void cboIncidentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIncidentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboIncidentTypeActionPerformed

    private void txtTimeExposedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeExposedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeExposedActionPerformed

    private void cboNatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNatureActionPerformed

    private void cboNatureItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNatureItemStateChanged
        
    }//GEN-LAST:event_cboNatureItemStateChanged

    private void txtActivityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtActivityKeyTyped
        statusOpen.setSelected(true);
        //statusPending.setEnabled(false);
        statusClosed.setEnabled(false);
        if(cboNature.getSelectedItem().toString().equals("Fatality")||cboNature.getSelectedItem().toString().equals("Above R50 000")){
        txtReferenceNumber.setBackground(Color.red);
        }
        setReferenceNumber();
        java.util.Date date = new java.util.Date();
        dcTodayDate.setDate(date);
        dcClosingDate.setDate(null);
    }//GEN-LAST:event_txtActivityKeyTyped

    private void dcClosingDateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcClosingDateMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcClosingDateMousePressed

    private void dcClosingDateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcClosingDateMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dcClosingDateMouseReleased

    private void dcClosingDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcClosingDateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dcClosingDateMouseClicked

    private void dcClosingDateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcClosingDateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dcClosingDateMouseEntered

    private void dcClosingDateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_dcClosingDateInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_dcClosingDateInputMethodTextChanged

    private void dcClosingDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcClosingDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dcClosingDatePropertyChange

    private void dcClosingDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcClosingDateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcClosingDateKeyPressed

    private void dcClosingDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcClosingDateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dcClosingDateKeyReleased

    private void cboAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAgentActionPerformed

    private void cboEmployeeNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEmployeeNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEmployeeNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Incident().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Incident.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox cboAgent;
    public static javax.swing.JComboBox cboEmployeeNumber;
    public static javax.swing.JComboBox cboHrs;
    public static javax.swing.JComboBox cboIncidentType;
    public static javax.swing.JComboBox cboNOCDW;
    public static javax.swing.JComboBox cboNature;
    public static javax.swing.JComboBox cboReportedTo;
    public static javax.swing.JComboBox cboShift;
    public static com.toedter.calendar.JDateChooser dcClosingDate;
    public static com.toedter.calendar.JDateChooser dcTodayDate;
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    public static com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JCheckBox statusClosed;
    public static javax.swing.JCheckBox statusOpen;
    public static javax.swing.JTextArea txtActivity;
    public static javax.swing.JTextField txtArea;
    public static javax.swing.JTextField txtContactNumber;
    public static javax.swing.JTextField txtDepartment;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtEquipmentDemaged;
    public static javax.swing.JTextField txtEquipmentUsed;
    public static javax.swing.JFormattedTextField txtEstimatedValue;
    public static javax.swing.JTextField txtIdNumber;
    public static javax.swing.JTextField txtName;
    public static javax.swing.JTextField txtReferenceNumber;
    public static javax.swing.JTextField txtSite;
    public static javax.swing.JTextField txtSurname;
    public static javax.swing.JTextField txtTimeExposed;
    public static javax.swing.JTextField txtYears;
    // End of variables declaration//GEN-END:variables
private String choice;
private String status;
}
