/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conceptium.biz;

import com.alee.laf.WebLookAndFeel;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author MathomeTD
 */
public class IncidentAnalysis extends javax.swing.JFrame {

    /**
     * Creates new form IncidentAnalysis
     */
    private static IncidentAnalysis obj = null;
    private IncidentAnalysis() {
        setUndecorated(true);
        setResizable(false);
        initComponents();
        reference();
    }
    public static IncidentAnalysis getObj(){
            if (obj == null){
                obj = new IncidentAnalysis();
            }
            return obj;
        }
   private void reference(){
        String sql ="Select * from Incident";
        
        String sql2= "select count as u from  login";
            try (Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
                PreparedStatement pst = con.prepareStatement(sql);){
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    String ID = rs.getString("ReferenceNumber");
                    cboRef.addItem(ID.trim());
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cboAbsent2 = new javax.swing.JComboBox();
        cboAbsent3 = new javax.swing.JComboBox();
        cboAbsent1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtDesc1 = new javax.swing.JTextField();
        txtDesc2 = new javax.swing.JTextField();
        txtDesc3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cboTeam = new javax.swing.JComboBox();
        txtTeamDesc2 = new javax.swing.JTextField();
        cboTeam2 = new javax.swing.JComboBox();
        cboTeam3 = new javax.swing.JComboBox();
        cboTeam1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtTeamDesc3 = new javax.swing.JTextField();
        txtTeamDesc1 = new javax.swing.JTextField();
        txtTeamDesc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTaskDesc = new javax.swing.JTextField();
        cboTask = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cboFactors2 = new javax.swing.JComboBox();
        cboFactors = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtFactors2 = new javax.swing.JTextField();
        txtFactors3 = new javax.swing.JTextField();
        txtFactors1 = new javax.swing.JTextField();
        cboFactors1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtEnvironmentDesc = new javax.swing.JTextField();
        cboEnvironment = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboRef = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cboAbsent2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Applicable","DF01:Guards or Barriers", "DF02:Detection Systems", "DF03:Warning Systems", "DF4:Protection system", "DF05:Recovery", "DF06:Escape", "DF07:Rescue", "SDF08:afety device operation", "DF09:Personal protective equipment", "DF10:Hazard indefication", "DF:11Control Systems", " " }));

        cboAbsent3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Applicable","DF01:Guards or Barriers", "DF02:Detection Systems", "DF03:Warning Systems", "DF4:Protection system", "DF05:Recovery", "DF06:Escape", "DF07:Rescue", "SDF08:afety device operation", "DF09:Personal protective equipment", "DF10:Hazard indefication", "DF:11Control Systems", " " }));

        cboAbsent1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Applicable","DF01:Guards or Barriers", "DF02:Detection Systems", "DF03:Warning Systems", "DF4:Protection system", "DF05:Recovery", "DF06:Escape", "DF07:Rescue", "SDF08:afety device operation", "DF09:Personal protective equipment", "DF10:Hazard indefication", "DF:11Control Systems", " " }));
        cboAbsent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAbsent1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Absent or failed defenses:");

        txtDesc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesc1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Description:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(cboAbsent2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboAbsent1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboAbsent3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)
                        .addGap(0, 343, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDesc3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDesc2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDesc1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboAbsent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDesc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboAbsent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboAbsent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDesc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cboTeam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Applicable","IT00 : Make a Selection", "IT01: Supervision", "IT02: Operating authority", "IT03: Operating speed", "IT04: Equipment use", "IT05: Personal protactive equipment", "IT06: Procedural compliance", "IT07: Change management", "IT08: Equipment/Materails handling", "IT09: Misconduct", "IT10: Work method", "IT11: Occupational hygine practices", "IT12: Hazard recognition/perception", "IT:13 Risk Management", "Other(specify)"}));
        cboTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTeamActionPerformed(evt);
            }
        });

        cboTeam2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Not Applicable","IT00 : Make a Selection", "IT01: Supervision", "IT02: Operating authority", "IT03: Operating speed", "IT04: Equipment use", "IT05: Personal protactive equipment", "IT06: Procedural compliance", "IT07: Change management", "IT08: Equipment/Materails handling", "IT09: Misconduct", "IT10: Work method", "IT11: Occupational hygine practices", "IT12: Hazard recognition/perception", "IT:13 Risk Management", "Other(specify)" }));

        cboTeam3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Not Applicable","IT00 : Make a Selection", "IT01: Supervision", "IT02: Operating authority", "IT03: Operating speed", "IT04: Equipment use", "IT05: Personal protactive equipment", "IT06: Procedural compliance", "IT07: Change management", "IT08: Equipment/Materails handling", "IT09: Misconduct", "IT10: Work method", "IT11: Occupational hygine practices", "IT12: Hazard recognition/perception", "IT:13 Risk Management", "Other(specify)" }));

        cboTeam1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Not Applicable","IT00 : Make a Selection", "IT01: Supervision", "IT02: Operating authority", "IT03: Operating speed", "IT04: Equipment use", "IT05: Personal protactive equipment", "IT06: Procedural compliance", "IT07: Change management", "IT08: Equipment/Materails handling", "IT09: Misconduct", "IT10: Work method", "IT11: Occupational hygine practices", "IT12: Hazard recognition/perception", "IT:13 Risk Management", "Other(specify)" }));

        jLabel2.setText("Individual / Team Actions:");

        txtTeamDesc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeamDesc3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Description:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(227, 227, 227)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboTeam, 0, 399, Short.MAX_VALUE)
                            .addComponent(cboTeam1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTeam3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTeam2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTeamDesc1)
                                    .addComponent(txtTeamDesc2)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTeamDesc3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTeamDesc))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeamDesc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeamDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeamDesc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTeam3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeamDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Task / Environmental conditions (Workplace)");

        cboTask.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Not Applicable", "TW01: Task Planning/preparation/manning", "TW02: Hazard analysis/JSA/Take 5", "TW03: Procedures - avalaibility and suitability", "TW04: Permit to work - availability and suitability", "TW05: Abnormal operational situation or condition", "TW06: Tools /equipment/materials", "TW07: Equipment intergrity", "TW08: House Keeping", "TWO09: Weather conditions", "TW10: Congestion/restriction/access", "TW11: routine/non routine task", "TW12: Fire and/or explosion hazard", "TW13: Lighting", "TW14: Temperature", "TW15: Noise", "TW16: Ventilation", "TW17: Pressure", "TW18: Gas, dust or fumes", "TW19: Radiation", "TW20:Chemical", "TW21: Training", "TW22:Wild life", "TW23: Surface gradient/conditions", "Other Specify" }));

        jLabel10.setText("Description:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cboTask, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTaskDesc))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaskDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cboFactors2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Applicable", "OS01: Leadership and accountability", "OS02: Legal requirements, committment and document control", "OS03: Risk and change management", "OS04: Planning, goals and targets", "OS05: Health and hygiene", "SO07: Communication, consult and participation", "SO08: Business conduct, human rights, community", "SO09: Design, construction and commisioning", "SO10: Operations and maintenance", "SO11: Suppliers, contractors and patners", "SO12: Stewardship", "SO13: Incident reporting and investigation", "SO14: Crisis and emergency management", "SO15: Monitoring, audit and review", "Others(specify)", " " }));

        cboFactors.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Applicable", "OS01: Leadership and accountability", "OS02: Legal requirements, committment and document control", "OS03: Risk and change management", "OS04: Planning, goals and targets", "OS05: Health and hygiene", "SO07: Communication, consult and participation", "SO08: Business conduct, human rights, community", "SO09: Design, construction and commisioning", "SO10: Operations and maintenance", "SO11: Suppliers, contractors and patners", "SO12: Stewardship", "SO13: Incident reporting and investigation", "SO14: Crisis and emergency management", "SO15: Monitoring, audit and review", "Others(specify)", " ", " ", " " }));
        cboFactors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFactorsActionPerformed(evt);
            }
        });

        jLabel5.setText("Organisational Factors:");

        txtFactors2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFactors2ActionPerformed(evt);
            }
        });

        cboFactors1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Applicable", "OS01: Leadership and accountability", "OS02: Legal requirements, committment and document control", "OS03: Risk and change management", "OS04: Planning, goals and targets", "OS05: Health and hygiene", "SO07: Communication, consult and participation", "SO08: Business conduct, human rights, community", "SO09: Design, construction and commisioning", "SO10: Operations and maintenance", "SO11: Suppliers, contractors and patners", "SO12: Stewardship", "SO13: Incident reporting and investigation", "SO14: Crisis and emergency management", "SO15: Monitoring, audit and review", "Others(specify)", " ", " ", " " }));
        cboFactors1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFactors1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Description:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboFactors2, javax.swing.GroupLayout.Alignment.LEADING, 0, 392, Short.MAX_VALUE)
                            .addComponent(cboFactors1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboFactors, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtFactors1)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFactors3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFactors2))
                                .addContainerGap())))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFactors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFactors1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFactors1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFactors2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFactors2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFactors3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cboEnvironment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Applicable", "HF01: Complisency/motivation/attitude", "HF02: Drugs/Alcohol influence", "HF03: Fatigue", "HF04: Time/ productivity pressures", "HF05: Peer pressure/ Supervisory example", "HF06:Physical/mental capabilities", "HF07: Physical/mental stress", "HF08: Personal issues", "HF09: Distraction/pre-occupation", "HF10: Compitence/experience/skills for task", "HF11: Poor inadequate communication", "HF12: Tolarance of violations", "HF13: Change of routine", "Other(specify)", " " }));
        cboEnvironment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEnvironmentActionPerformed(evt);
            }
        });

        jLabel11.setText("Task / Environmental conditions (Human)");

        jLabel12.setText("Description:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cboEnvironment, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtEnvironmentDesc))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEnvironment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnvironmentDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel4.setText("Reference Number:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboRef, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("Add the incident Analysis");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add Root Cause");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTeamActionPerformed

    private void txtFactors2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFactors2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFactors2ActionPerformed

    private void cboAbsent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAbsent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAbsent1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql = "insert into IncidentAnalysis(ReferenceNumber,Absent1,Absent2,Absent3,Team,Team1,Team2,Team3,"+
                "Task,Environment,Factors,Factor1,Factor2,Desc0,Desc1,Desc2,TeamDesc,TeamDesc1,TeamDes2,TeamdDesc3,"+
                "TaskDesc,EnviromentDesc,FactorsDesc,FactorsDesc1,FacorsDesc2)"+
                "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        String reference = cboRef.getSelectedItem().toString();
        String absent1 = cboAbsent1.getSelectedItem().toString();
        String absent2 = cboAbsent2.getSelectedItem().toString();
        String absent3 = cboAbsent3.getSelectedItem().toString();
        String team = cboTeam.getSelectedItem().toString();
        String team1 = cboTeam1.getSelectedItem().toString();
        String team2 = cboTeam2.getSelectedItem().toString();
        String team3 = cboTeam3.getSelectedItem().toString();
        String task = cboTask.getSelectedItem().toString();
        String environment = cboEnvironment.getSelectedItem().toString();
        String factors = cboFactors.getSelectedItem().toString();
        String factors1 = cboFactors.getSelectedItem().toString();
        String factors2 = cboFactors.getSelectedItem().toString();
        String desc = txtDesc1.getText();
        String desc1 = txtDesc2.getText();
        String desc2 = txtDesc3.getText();
        String teamDisc = txtTeamDesc.getText();
        String teamDisc1 = txtTeamDesc1.getText();
        String teamDisc2 = txtTeamDesc2.getText();
        String teamDisc3 = txtTeamDesc3.getText();
        String taskDesc = txtTaskDesc.getText();
        String environmentDesc = txtEnvironmentDesc.getText();
        String factorsDesc = txtFactors1.getText();
        String factorsDesc1 = txtFactors2.getText();
        String factorsDesc2 = txtFactors3.getText();
        try{
            Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, reference);
            pst.setString(2, absent1);
            pst.setString(3, absent2);
            pst.setString(4, absent3);
            pst.setString(5, team);
            pst.setString(6, team1);
            pst.setString(7,team2);
            pst.setString(8, team3);
            pst.setString(9, task);
            pst.setString(10, environment);
            pst.setString(11, factors);
            pst.setString(12, factors1);
            pst.setString(13, factors2);
            pst.setString(14, desc);
            pst.setString(15, desc1);
            pst.setString(16, desc2);
            pst.setString(17, teamDisc);
            pst.setString(18, teamDisc1);
            pst.setString(19, teamDisc2);
            pst.setString(20, teamDisc3);
            pst.setString(21, taskDesc);
            pst.setString(22, environmentDesc);
            pst.setString(23, factorsDesc);
            pst.setString(24, factorsDesc1);
            pst.setString(25, factorsDesc2);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(IncidentAnalysis.this, "Analysis successfully save.");
        }
        catch(SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(IncidentAnalysis.this, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboFactorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFactorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboFactorsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RootCause rR = RootCause.getObj();
        rR.cboReference.setSelectedItem(cboRef.getSelectedItem().toString().trim());
        RootCause.getObj().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cboFactors1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFactors1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboFactors1ActionPerformed

    private void cboEnvironmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEnvironmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEnvironmentActionPerformed

    private void txtTeamDesc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeamDesc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeamDesc3ActionPerformed

    private void txtDesc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesc1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncidentAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncidentAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncidentAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncidentAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncidentAnalysis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboAbsent1;
    private javax.swing.JComboBox cboAbsent2;
    private javax.swing.JComboBox cboAbsent3;
    private javax.swing.JComboBox cboEnvironment;
    private javax.swing.JComboBox cboFactors;
    private javax.swing.JComboBox cboFactors1;
    private javax.swing.JComboBox cboFactors2;
    private javax.swing.JComboBox cboRef;
    private javax.swing.JComboBox cboTask;
    private javax.swing.JComboBox cboTeam;
    private javax.swing.JComboBox cboTeam1;
    private javax.swing.JComboBox cboTeam2;
    private javax.swing.JComboBox cboTeam3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtDesc1;
    private javax.swing.JTextField txtDesc2;
    private javax.swing.JTextField txtDesc3;
    private javax.swing.JTextField txtEnvironmentDesc;
    private javax.swing.JTextField txtFactors1;
    private javax.swing.JTextField txtFactors2;
    private javax.swing.JTextField txtFactors3;
    private javax.swing.JTextField txtTaskDesc;
    private javax.swing.JTextField txtTeamDesc;
    private javax.swing.JTextField txtTeamDesc1;
    private javax.swing.JTextField txtTeamDesc2;
    private javax.swing.JTextField txtTeamDesc3;
    // End of variables declaration//GEN-END:variables
}
