/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conceptium.biz;

import com.alee.laf.WebLookAndFeel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MathomeTD
 */
public class IncidentRegistry extends javax.swing.JFrame {

    /**
     * Creates new form IncidentRegistry
     */
    private static IncidentRegistry obj = null;
    private IncidentRegistry() throws SQLException, ClassNotFoundException {
        setResizable(false);
        setUndecorated(true);
        initComponents();
        updateTable();
    }
    public static IncidentRegistry getObj() throws SQLException, ClassNotFoundException{
            if (obj == null){
                obj = new IncidentRegistry();
            }
            return obj;
        }
private void updateTable() throws SQLException,ClassNotFoundException{
       String sql = "Select ReferenceNumber,Name,Surname,IDNumber,Site,ReportedTo,IncidentType,"+
               "NatureOfIncident,DateOfIncident,DateOfReportingIncident,TodayDate from Incident "+
                   "where status = ?";
       String search = "Open";
       try {
           Connection con = DbConnection.dbConnection();
           PreparedStatement pst = con.prepareStatement(sql);
           pst.setString(1, search);
           ResultSet rs = pst.executeQuery();
           jXTable1.setModel(DbUtils.resultSetToTableModel(rs)); 
       }
       catch (ClassNotFoundException | SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
       }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        incidentInformation = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        incidentDescription = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        incidentRiskRating = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        incidentAnalysis = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        incidentCorrectiveAction = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        deleteIncident = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable(){public boolean isCellEditable(int row, int column){
            return false;}};
    jPanel2 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();

    jPopupMenu1.add(jSeparator4);

    incidentInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/preview.png"))); // NOI18N
    incidentInformation.setText("View Incident Information");
    incidentInformation.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            incidentInformationActionPerformed(evt);
        }
    });
    jPopupMenu1.add(incidentInformation);
    jPopupMenu1.add(jSeparator6);

    incidentDescription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/preview.png"))); // NOI18N
    incidentDescription.setText("View Incident Description");
    incidentDescription.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            incidentDescriptionActionPerformed(evt);
        }
    });
    jPopupMenu1.add(incidentDescription);
    jPopupMenu1.add(jSeparator5);

    incidentRiskRating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/preview.png"))); // NOI18N
    incidentRiskRating.setText("View incident Risk Rating");
    jPopupMenu1.add(incidentRiskRating);
    jPopupMenu1.add(jSeparator3);

    incidentAnalysis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/preview.png"))); // NOI18N
    incidentAnalysis.setText("View Incident Analysis");
    jPopupMenu1.add(incidentAnalysis);
    jPopupMenu1.add(jSeparator2);

    incidentCorrectiveAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/preview.png"))); // NOI18N
    incidentCorrectiveAction.setText("View Incident Corrective Action");
    incidentCorrectiveAction.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            incidentCorrectiveActionActionPerformed(evt);
        }
    });
    jPopupMenu1.add(incidentCorrectiveAction);
    jPopupMenu1.add(jSeparator1);

    deleteIncident.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/delete.png"))); // NOI18N
    deleteIncident.setText("Delete Incident");
    jPopupMenu1.add(deleteIncident);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setAlwaysOnTop(true);

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/close.png"))); // NOI18N
    jButton1.setText("Close");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jXTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            jXTable1MouseReleased(evt);
        }
    });
    jScrollPane2.setViewportView(jXTable1);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jXSearchField1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0))
        .addComponent(jScrollPane2)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(3, 3, 3)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
            .addGap(3, 3, 3)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jXSearchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(3, 3, 3))
    );

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 51, Short.MAX_VALUE)
    );

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 29, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, 0)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void incidentCorrectiveActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incidentCorrectiveActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incidentCorrectiveActionActionPerformed

    private void incidentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incidentInformationActionPerformed
        try{                                                    
            int row = jXTable1.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel)jXTable1.getModel();
            String selected = model.getValueAt(row, 0).toString();
            //Incident incident = new Incident();
            Incident.cboEmployeeNumber.removeAllItems();
            try{
                Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
                PreparedStatement pst = con.prepareStatement("Select * from Incident where ReferenceNumber = ?");
                pst.setString(1, selected);
                ResultSet rs = pst.executeQuery();
                if (rs.next()){
                    String employeeNumber = rs.getString("EmployeeNumber");
                    Incident.cboEmployeeNumber.addItem(employeeNumber);
                    String name = rs.getString("Name");
                    Incident.txtName.setText(name.trim());
                    String surname = rs.getString("Surname");
                    Incident.txtSurname.setText(surname.trim());
                    String idNumber = rs.getString("IDNumber");
                    Incident.txtIdNumber.setText(idNumber);
                    
                    //String ID = rs.getString("ContactNumber");
                    //Incident.txtContactNumber.setText(ID.trim());
                    //String email = rs.getString("EmailAddress");
                    //Incident.txtEmail.setText(email.trim());
                    //String department = rs.getString("Department");
                    //Incident.txtDepartment.setText(department.trim());
                    //String site = rs.getString("Site");
                    //Incident.txtSite.setText(site.trim());
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(IncidentRegistry.this, e);
            }
            Incident iI = new Incident();
            iI.setVisible(true);
            //Incident.getObj().setVisible(true);
        }
        catch(SQLException ex){
            Logger.getLogger(IncidentRegistry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_incidentInformationActionPerformed

    private void incidentDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incidentDescriptionActionPerformed
        int row = jXTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jXTable1.getModel();
        String selected = model.getValueAt(row, 0).toString();
        //IncidentDetails incident = new IncidentDetails();
        IncidentDetails.cboReference.setSelectedItem(selected);
        IncidentDetails.getObj().setVisible(true);
    }//GEN-LAST:event_incidentDescriptionActionPerformed

    private void jXTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTable1MouseReleased
        jXTable1.setComponentPopupMenu(jPopupMenu1);
        if (evt.isPopupTrigger())
        {
            jPopupMenu1.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jXTable1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncidentRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncidentRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncidentRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncidentRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new IncidentRegistry().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(IncidentRegistry.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(IncidentRegistry.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem deleteIncident;
    private javax.swing.JMenuItem incidentAnalysis;
    private javax.swing.JMenuItem incidentCorrectiveAction;
    private javax.swing.JMenuItem incidentDescription;
    private javax.swing.JMenuItem incidentInformation;
    private javax.swing.JMenuItem incidentRiskRating;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables
}
