/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conceptium.biz;

import static conceptium.biz.Incident.jDateChooser2;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author MathomeTD
 */
public class InternalAudits extends javax.swing.JFrame {

    /**
     * Creates new form InternalAudits
     */
    private static InternalAudits obj = null;
    private InternalAudits() {
        setUndecorated(true);
        setResizable(false);
        initComponents();
        fillId();
        site();
    }
    
    private void fillId(){
        String sql ="Select * from Persons";
            try {
                Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    String ID = rs.getString("EmployeeNumber");
                    cboEmployeeNumber.addItem(ID.trim());
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
      private void site(){
        String sql ="Select * from Site";
            try {
                Connection con = DriverManager.getConnection("jdbc:derby:Incident","herbert","elsie1*#");
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while(rs.next()){
                    String ID = rs.getString("sitename");
                    cboSite.addItem(ID.trim());
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
public static InternalAudits getObj(){
            if (obj == null){
                obj = new InternalAudits();
            }
            return obj;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtReferenceNumber = new javax.swing.JTextField();
        txtRequirement = new javax.swing.JTextField();
        dcTodayDate = new com.toedter.calendar.JDateChooser();
        txtAction = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGap = new javax.swing.JTextArea();
        txtUpload = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cboEmployeeNumber = new javax.swing.JComboBox();
        dcDueDate = new com.toedter.calendar.JDateChooser();
        cboSite = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Open = new javax.swing.JCheckBox();
        Pending = new javax.swing.JCheckBox();
        Closed = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cboOperation = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cboAuditType = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Reference:");

        jLabel2.setText("Date:");

        jLabel3.setText("Requirement:");

        jLabel4.setText("GAP:");

        jLabel5.setText("Action:");

        jLabel6.setText("Responsible person:");

        jLabel7.setText("Dute Date:");

        jLabel8.setText("Status:");

        txtRequirement.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                //format.format(Integer.parseInt(txtTest.getText();
                    //System.out.println(format.format(Integer.parseInt(txtTest.getText())));
                    //jFormattedTextField1.setValue(Double.parseDouble((txtTest.getText())));
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    //format.format(Integer.parseInt(txtTest.getText();
                        //System.out.println(format.format(Integer.parseInt(txtTest.getText())));
                        //jFormattedTextField1.setValue(Double.parseDouble(txtTest.getText()));
                        Open.setEnabled(true);
                    }

                    @Override
                    public void changedUpdate(DocumentEvent e) {
                        //format.format(Integer.parseInt(txtTest.getText();
                            //System.out.println(format.format(Integer.parseInt(txtTest.getText())));
                            //jFormattedTextField1.setValue(Double.parseDouble(txtTest.getText()));
                            Open.setEnabled(true);
                        }
                    });
                    txtRequirement.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            txtRequirementActionPerformed(evt);
                        }
                    });
                    txtRequirement.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                            txtRequirementKeyTyped(evt);
                        }
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                            txtRequirementKeyPressed(evt);
                        }
                    });

                    txtAction.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            txtActionActionPerformed(evt);
                        }
                    });

                    txtGap.setColumns(20);
                    txtGap.setRows(5);
                    txtGap.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                            txtGapKeyPressed(evt);
                        }
                    });
                    jScrollPane1.setViewportView(txtGap);

                    jButton1.setText("search");
                    jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton1ActionPerformed(evt);
                        }
                    });

                    cboSite.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            cboSiteActionPerformed(evt);
                        }
                    });

                    jLabel9.setText("Site:");

                    jLabel10.setText("Report:");

                    Open.setText("Open");
                    Open.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                            OpenItemStateChanged(evt);
                        }
                    });
                    Open.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            OpenActionPerformed(evt);
                        }
                    });

                    Pending.setText("Pending");
                    Pending.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            PendingActionPerformed(evt);
                        }
                    });

                    Closed.setText("Closed");
                    Closed.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ClosedActionPerformed(evt);
                        }
                    });

                    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                    jPanel1.setLayout(jPanel1Layout);
                    jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(62, 62, 62)
                                            .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(46, 46, 46)
                                            .addComponent(jLabel3))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(jLabel4)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtRequirement)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtReferenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dcTodayDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(85, 85, 85)
                                            .addComponent(jLabel5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAction, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cboEmployeeNumber, 0, 205, Short.MAX_VALUE)
                                                .addComponent(cboSite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dcDueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(Open)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(Pending)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(Closed)
                                                    .addGap(0, 0, Short.MAX_VALUE)))))))
                            .addContainerGap())
                    );
                    jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtReferenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addComponent(dcTodayDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtRequirement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUpload)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cboEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addComponent(dcDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(cboSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(Open)
                                .addComponent(Pending)
                                .addComponent(Closed))
                            .addContainerGap())
                    );

                    btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/save.png"))); // NOI18N
                    btnSave.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnSaveActionPerformed(evt);
                        }
                    });

                    btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/close.png"))); // NOI18N
                    btnClose.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnCloseActionPerformed(evt);
                        }
                    });

                    btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dbase/Resources/edit.png"))); // NOI18N
                    btnEdit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnEditActionPerformed(evt);
                        }
                    });

                    jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                    jLabel11.setText("Audit Type:");

                    cboOperation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Audit", "Inspection" }));
                    cboOperation.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                            cboOperationItemStateChanged(evt);
                        }
                    });

                    jLabel12.setText("Select Operation:");

                    cboAuditType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Internal Audit", "External Audit" }));

                    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                    jPanel2.setLayout(jPanel2Layout);
                    jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboOperation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(51, 51, 51)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboAuditType, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                    );
                    jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboAuditType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(cboOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addContainerGap())
                    );

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
                    );
                    layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSave)
                                .addComponent(btnClose)
                                .addComponent(btnEdit))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );

                    pack();
                    setLocationRelativeTo(null);
                }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser x = new JFileChooser();
        x.showOpenDialog(InternalAudits.getObj());
        File f = x.getSelectedFile();
        filename = f.getAbsolutePath();
        if(txtUpload == null){
        JOptionPane.showConfirmDialog(InternalAudits.this, "No selection was made please try again");
        }else{
            txtUpload.setText(filename);
        String path = filename;
        String newpath = path.replace('\\', '/');
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String reference = txtReferenceNumber.getText();
        java.sql.Date today = new java.sql.Date(dcTodayDate.getDate().getTime());
        String requirement = txtRequirement.getText();
        String gap = txtGap.getText();
        String action = txtAction.getText();
        String responsiblePerson = cboEmployeeNumber.getSelectedItem().toString();
        java.sql.Date dueDate = new java.sql.Date(dcDueDate.getDate().getTime());
        String site = cboSite.getSelectedItem().toString();
        String operation = cboOperation.getSelectedItem().toString();
        String auditType = (String)cboAuditType.getSelectedItem();
        if("Audit".equals(operation)){
        //String status = txtStatus.getText();
        String sql = "Insert into INTERNALAUDITS(AUDITTYPE,REFERENCENUMBER, TODAY,REQUIREMENT,GAP,ACTION"+
                "RESPONSIBLEPERSON,DUEDATE,SITE,STATUS,DOCS,TODAYSDATE)values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection con = DriverManager.getConnection("jdbc:derby:MTD", "herbert", "elsie1*#");
            PreparedStatement pst = con.prepareStatement(sql);){
            pst.setString(1, auditType);
            pst.setString(2, reference);
            pst.setDate(3, today);
            pst.setString(4, requirement);
            pst.setString(5, gap);
            pst.setString(6, action);
            pst.setString(7, responsiblePerson);
            pst.setDate(8, dueDate);
            pst.setString(9, site);
            pst.setString(10, choice);
            String path = filename;
            String newpath = path.replace('\\', '/');
            File newpdf = new File(newpath);
            FileInputStream fi = new FileInputStream(newpdf);
            pst.setBinaryStream(11, fi);
            pst.setDate(12, today);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(InternalAudits.getObj(), "Record successfully saved");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(InternalAudits.getObj(), ex);
        }
        }
        else{
            String sql1 = "Insert into INSPECTIONS(REFERENCENUMBER, TODAY,REQUIREMENT,GAP,ACTION"+
                "RESPONSIBLEPERSON,DUEDATE,SITE,STATUS,DOCS)values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection con = DriverManager.getConnection("jdbc:derby:MTD", "herbert", "elsie1*#");
            PreparedStatement pst = con.prepareStatement(sql1);){
            pst.setString(1, reference);
            pst.setDate(2, today);
            pst.setString(3, requirement);
            pst.setString(4, gap);
            pst.setString(5, action);
            pst.setString(6, responsiblePerson);
            pst.setDate(7, dueDate);
            pst.setString(8, site);
            pst.setString(9, choice);
            String path = filename;
            String newpath = path.replace('\\', '/');
            File newpdf = new File(newpath);
            FileInputStream fi = new FileInputStream(newpdf);
            pst.setBinaryStream(10, fi);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(InternalAudits.getObj(), "Record successfully saved");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(InternalAudits.getObj(), ex);
        }
        }
        btnEdit.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        java.util.Date date = new java.util.Date();
        dcTodayDate.setDate(date);
        Calendar c = Calendar.getInstance();
        c.setTime(date);
        c.add(Calendar.DATE, 30);
        dcDueDate.setDate(c.getTime());
        dcDueDate.setEnabled(false);
        dcTodayDate.setEnabled(false);
        txtReferenceNumber.setBackground(Color.RED);
        txtReferenceNumber.setFont(new Font("Arial", Font.BOLD, 14));
        
    }//GEN-LAST:event_formWindowActivated

    private void txtRequirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRequirementActionPerformed
        
    }//GEN-LAST:event_txtRequirementActionPerformed

    private void txtGapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGapKeyPressed
        txtGap.setLineWrap(true);
        txtGap.setWrapStyleWord(true);
    }//GEN-LAST:event_txtGapKeyPressed

    private void cboSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSiteActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        choice = "Open";
        if(Open.isSelected()){
        Pending.setEnabled(false);
        Closed.setEnabled(false);
        }else{
            Pending.setEnabled(true);
        Closed.setEnabled(true);
        }
    }//GEN-LAST:event_OpenActionPerformed

    private void PendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingActionPerformed
        choice = "Pending";
        if(Pending.isSelected()){
        Open.setEnabled(false);
        Closed.setEnabled(false);
        }else{
            Open.setEnabled(true);
        Closed.setEnabled(true);
        }
    }//GEN-LAST:event_PendingActionPerformed

    private void ClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosedActionPerformed
        choice = "Closed";
        if(Closed.isSelected()){
        Pending.setEnabled(false);
        Open.setEnabled(false);
        }else{
            Pending.setEnabled(true);
        Open.setEnabled(true);
        }
    }//GEN-LAST:event_ClosedActionPerformed

    private void OpenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OpenItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenItemStateChanged

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        AuditCorrective.jButton3.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtRequirementKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRequirementKeyPressed

    }//GEN-LAST:event_txtRequirementKeyPressed

    private void txtRequirementKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRequirementKeyTyped
        Open.setSelected(true);
        Open.setEnabled(false);
        Pending.setEnabled(false);
        Closed.setEnabled(false);
        btnEdit.setEnabled(false);
    }//GEN-LAST:event_txtRequirementKeyTyped

    private void cboOperationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboOperationItemStateChanged
        if("Inspection".equals(cboOperation.getSelectedItem().toString())){
        cboAuditType.setEnabled(false);
        }else{
            cboAuditType.setEnabled(true);
        }
    }//GEN-LAST:event_cboOperationItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InternalAudits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InternalAudits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InternalAudits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InternalAudits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InternalAudits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox Closed;
    public static javax.swing.JCheckBox Open;
    public javax.swing.JCheckBox Pending;
    public javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    public javax.swing.JButton btnSave;
    private javax.swing.JComboBox cboAuditType;
    public static javax.swing.JComboBox cboEmployeeNumber;
    private javax.swing.JComboBox cboOperation;
    public static javax.swing.JComboBox cboSite;
    public static com.toedter.calendar.JDateChooser dcDueDate;
    public static com.toedter.calendar.JDateChooser dcTodayDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtAction;
    public static javax.swing.JTextArea txtGap;
    public static javax.swing.JTextField txtReferenceNumber;
    public static javax.swing.JTextField txtRequirement;
    private javax.swing.JTextField txtUpload;
    // End of variables declaration//GEN-END:variables
String filename;
    int z = 0;
    byte[] document = null;
    byte[] userpdf = null;
    FileInputStream fis;
    String choice;
}
