

DROP TABLE APP.BOOKCOURSE;


CREATE TABLE APP.BOOKCOURSE(
"IDPASSPORT" VARCHAR(15),
"LEARNERID" VARCHAR(15),
"NAME" VARCHAR(100), 
"SURNAME" VARCHAR(100), 
"OFOOCCUPATIONLEVEL" VARCHAR(100),
"OFOSPECIALISATION" VARCHAR(100),
"COURSEBOOKED" VARCHAR(200),
"STARTDATE" DATE,
"COURSELENGTH" VARCHAR(10),  
"DATENOW" DATE,
"SITE" VARCHAR(50),
"ENDDATE" DATE, 
"TRANSACTIONID" VARCHAR(100), 
"FACILITATOR" VARCHAR(100),
"COSTCENTRE" VARCHAR(50)
);